# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  job1:
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.set-matrix.outputs.matrix }}
    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0  
    - id: set-matrix
      run: |
        data=$(bash fetch.sh)
        echo $data
        echo "matrix=$data" >> $GITHUB_OUTPUT 
  act:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    needs: job1
    strategy:
      matrix: 
        version: "${{ fromJson(needs.job1.outputs.matrix) }}"
    steps:
      - uses: actions/checkout@v3
      - name: Do something
        run: echo ${{ matrix.version }}
      - name: Create new branch
        uses: peterjgrainger/action-create-branch@v2.2.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          branch: v${{ matrix.version }}
      - name: download phar.asc
        run: curl https://phar.phpunit.de/phpunit-${{ matrix.version }}.phar.asc -o bin/phpunit.phar.asc
      - name: download phar
        run: curl https://phar.phpunit.de/phpunit-${{ matrix.version }}.phar -o bin/phpunit.phar
          
      - uses: stefanzweifel/git-auto-commit-action@v4
        with:
          branch: v${{ matrix.version }}
          tagging_message: ${{ matrix.version }}
          create_branch: true
    

      
